name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args:  "pandoc --pdf-engine=xelatex -s rapport.md -o rapport.pdf" 
      - run : rapport.pdf >> output
        
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
